#!/usr/bin/perl

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use warnings;
use strict;
use JSON;
use esmith::ConfigDB;

require "/usr/libexec/nethserver/api/lib/helper_functions.pl";

my $input = readInput();
my $nic = $input->{'nic'};


open(FH, "arp-scan -I $nic -lx|");
my @ret;
while (<FH>) {
    chomp;
    my ($ip,$mac,$name) = split('\t');
    push(@ret, { ip => $ip, mac => $mac, name => $name});
}
close(FH);
print encode_json(\@ret);
